/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as CartImport } from './routes/cart'
import { Route as IndexImport } from './routes/index'
import { Route as WomenClothingImport } from './routes/women/clothing'
import { Route as WomenProductIdImport } from './routes/women/$productId'
import { Route as TechnologyProductsImport } from './routes/technology/products'
import { Route as TechnologyProductIdImport } from './routes/technology/$productId'
import { Route as MenClothingImport } from './routes/men/clothing'
import { Route as MenProductIdImport } from './routes/men/$productId'
import { Route as KidsClothingImport } from './routes/kids/clothing'
import { Route as KidsProductIdImport } from './routes/kids/$productId'

// Create/Update Routes

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WomenClothingRoute = WomenClothingImport.update({
  path: '/women/clothing',
  getParentRoute: () => rootRoute,
} as any)

const WomenProductIdRoute = WomenProductIdImport.update({
  path: '/women/$productId',
  getParentRoute: () => rootRoute,
} as any)

const TechnologyProductsRoute = TechnologyProductsImport.update({
  path: '/technology/products',
  getParentRoute: () => rootRoute,
} as any)

const TechnologyProductIdRoute = TechnologyProductIdImport.update({
  path: '/technology/$productId',
  getParentRoute: () => rootRoute,
} as any)

const MenClothingRoute = MenClothingImport.update({
  path: '/men/clothing',
  getParentRoute: () => rootRoute,
} as any)

const MenProductIdRoute = MenProductIdImport.update({
  path: '/men/$productId',
  getParentRoute: () => rootRoute,
} as any)

const KidsClothingRoute = KidsClothingImport.update({
  path: '/kids/clothing',
  getParentRoute: () => rootRoute,
} as any)

const KidsProductIdRoute = KidsProductIdImport.update({
  path: '/kids/$productId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/kids/$productId': {
      id: '/kids/$productId'
      path: '/kids/$productId'
      fullPath: '/kids/$productId'
      preLoaderRoute: typeof KidsProductIdImport
      parentRoute: typeof rootRoute
    }
    '/kids/clothing': {
      id: '/kids/clothing'
      path: '/kids/clothing'
      fullPath: '/kids/clothing'
      preLoaderRoute: typeof KidsClothingImport
      parentRoute: typeof rootRoute
    }
    '/men/$productId': {
      id: '/men/$productId'
      path: '/men/$productId'
      fullPath: '/men/$productId'
      preLoaderRoute: typeof MenProductIdImport
      parentRoute: typeof rootRoute
    }
    '/men/clothing': {
      id: '/men/clothing'
      path: '/men/clothing'
      fullPath: '/men/clothing'
      preLoaderRoute: typeof MenClothingImport
      parentRoute: typeof rootRoute
    }
    '/technology/$productId': {
      id: '/technology/$productId'
      path: '/technology/$productId'
      fullPath: '/technology/$productId'
      preLoaderRoute: typeof TechnologyProductIdImport
      parentRoute: typeof rootRoute
    }
    '/technology/products': {
      id: '/technology/products'
      path: '/technology/products'
      fullPath: '/technology/products'
      preLoaderRoute: typeof TechnologyProductsImport
      parentRoute: typeof rootRoute
    }
    '/women/$productId': {
      id: '/women/$productId'
      path: '/women/$productId'
      fullPath: '/women/$productId'
      preLoaderRoute: typeof WomenProductIdImport
      parentRoute: typeof rootRoute
    }
    '/women/clothing': {
      id: '/women/clothing'
      path: '/women/clothing'
      fullPath: '/women/clothing'
      preLoaderRoute: typeof WomenClothingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CartRoute,
  SearchRoute,
  KidsProductIdRoute,
  KidsClothingRoute,
  MenProductIdRoute,
  MenClothingRoute,
  TechnologyProductIdRoute,
  TechnologyProductsRoute,
  WomenProductIdRoute,
  WomenClothingRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cart",
        "/search",
        "/kids/$productId",
        "/kids/clothing",
        "/men/$productId",
        "/men/clothing",
        "/technology/$productId",
        "/technology/products",
        "/women/$productId",
        "/women/clothing"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/kids/$productId": {
      "filePath": "kids/$productId.tsx"
    },
    "/kids/clothing": {
      "filePath": "kids/clothing.tsx"
    },
    "/men/$productId": {
      "filePath": "men/$productId.tsx"
    },
    "/men/clothing": {
      "filePath": "men/clothing.tsx"
    },
    "/technology/$productId": {
      "filePath": "technology/$productId.tsx"
    },
    "/technology/products": {
      "filePath": "technology/products.tsx"
    },
    "/women/$productId": {
      "filePath": "women/$productId.tsx"
    },
    "/women/clothing": {
      "filePath": "women/clothing.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
